// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5CKh2HOlqG24xcTJ9sjWEpuwZINmsPyw',
    appId: '1:913450293567:web:77f43a01ecf86dd4c3db8a',
    messagingSenderId: '913450293567',
    projectId: 'ljrrt-ljrrt',
    authDomain: 'ljrrt-ljrrt.firebaseapp.com',
    storageBucket: 'ljrrt-ljrrt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDrVn4kwOcgkSOvJ7L43DrsiqIrIrqAyE',
    appId: '1:913450293567:android:c6a37b028de8258cc3db8a',
    messagingSenderId: '913450293567',
    projectId: 'ljrrt-ljrrt',
    storageBucket: 'ljrrt-ljrrt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwGvJ1K_bEWxBA2p9wgmWloduxthh87hY',
    appId: '1:913450293567:ios:e9ce6c4d598399e3c3db8a',
    messagingSenderId: '913450293567',
    projectId: 'ljrrt-ljrrt',
    storageBucket: 'ljrrt-ljrrt.appspot.com',
    iosBundleId: 'com.ljrrt.ljrrt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwGvJ1K_bEWxBA2p9wgmWloduxthh87hY',
    appId: '1:913450293567:ios:302f0f5bf4c3ab04c3db8a',
    messagingSenderId: '913450293567',
    projectId: 'ljrrt-ljrrt',
    storageBucket: 'ljrrt-ljrrt.appspot.com',
    iosBundleId: 'com.ljrrt.ljrrt.RunnerTests',
  );
}
